websites:
  - aldolushkja.it
  - lushkja.it
  - auth0.aldolushkja.it
output_file: README.md
max_workers: 2
timeout: 30
github_workflow_badge: https://github.com/aldo-lushkja/websites-monitor/actions/workflows/create-report.yml/badge.svg
